import Navlink from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <nav>

        <div className='logo-div'>
          <h2>LOGO</h2>
        </div>

          <ul>
            <li><Navlink href='/login' className = 'active'>LOGIN</Navlink></li>
            <li><Navlink href='/register' className = 'active'>REGISTER</Navlink></li>
            <li><Navlink href='/contact' className = 'active'>CONTACT</Navlink></li>
          </ul>
        </nav>

        {children}
        </body>
    </html>
  )
}
